# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='手机类型 0 ANDROID， 1 IOS', verbose_name='手机类型 0 ANDROID， 1 IOS')),
                ('uuid', models.CharField(help_text='设备ID', max_length=100, unique=True, verbose_name='设备ID')),
                ('tag', models.CharField(blank=True, help_text='编号', max_length=30, null=True, verbose_name='编号')),
                ('status', models.IntegerField(choices=[(0, 'online'), (2, 'disabled'), (1, 'offline')], default=0, help_text='手机状态', verbose_name='手机状态')),
                ('is_idle', models.BooleanField(default=True, help_text='是否空闲 布尔值', verbose_name='是否空闲')),
                ('can_recharge', models.BooleanField(default=False, help_text='可否充值 布尔值', verbose_name='可否充值')),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True, verbose_name='上次心跳的时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建手机时间', verbose_name='创建手机时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改手机时间', verbose_name='修改手机时间')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phone',
            },
        ),
        migrations.CreateModel(
            name='Slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(help_text='设备ID', max_length=100, unique=True, verbose_name='设备ID')),
                ('ip', models.CharField(help_text='ip', max_length=20, verbose_name='ip')),
                ('status', models.IntegerField(choices=[(0, 'online'), (1, 'offline')], default=0, help_text='主机状态 0 在线 ,1 离线', verbose_name='主机状态')),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True, verbose_name='上次心跳的时间戳')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建主机时间', verbose_name='创建主机时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改主机时间', verbose_name='修改主机时间')),
            ],
            options={
                'verbose_name': 'Slave',
                'verbose_name_plural': 'Slave',
            },
        ),
    ]
