# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='country',
            field=models.ForeignKey(blank=True, help_text='国家', null=True, on_delete=django.db.models.deletion.CASCADE, to='task.Country', verbose_name='国家'),
        ),
        migrations.AddField(
            model_name='phone',
            name='slave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Slave', verbose_name='主机'),
        ),
    ]
