# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-28 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20190627_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(0, 'online'), (1, 'offline'), (2, 'disabled')], default=0, help_text='手机状态', verbose_name='手机状态'),
        ),
    ]
