# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_auto_20190628_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(1, 'offline'), (2, 'disabled'), (0, 'online')], default=0, help_text='手机状态', verbose_name='手机状态'),
        ),
    ]
