# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-29 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_auto_20190628_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='is_stop',
            field=models.BooleanField(default=False, help_text='是否暂停', verbose_name='是否暂停'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(1, 'offline'), (2, 'disabled'), (0, 'online')], default=0, help_text='手机状态', verbose_name='手机状态'),
        ),
    ]
