# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20190629_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(2, 'disabled'), (1, 'offline'), (0, 'online')], default=0, help_text='手机状态', verbose_name='手机状态'),
        ),
    ]
