# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_auto_20190709_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(1, 'offline'), (0, 'online'), (2, 'disabled')], default=0, help_text='手机状态', verbose_name='手机状态'),
        ),
    ]
