# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20190710_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='platform',
            field=models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='手机类型 0 ANDROID， 1 IOS', verbose_name='手机类型 0 ANDROID， 1 IOS'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='status',
            field=models.IntegerField(choices=[(2, 'disabled'), (0, 'online'), (1, 'offline')], default=0, help_text='手机状态', verbose_name='手机状态'),
        ),
    ]
