# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-20 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, verbose_name='账户名')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='有域名的账户')),
                ('email', models.EmailField(default='', max_length=254)),
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态 True启用；False停用', verbose_name='状态 True启用；False停用')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_dt', models.DateTimeField(auto_now=True, verbose_name='最后一次修改')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否为超级用户')),
                ('superuser_level', models.IntegerField(default=0, verbose_name='超级用户级别')),
                ('timezone', models.IntegerField(default=0, help_text='时区, 从-12到+12', verbose_name='时区, 时区, 从-12到+12')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
