# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_url',
            field=models.CharField(default='', help_text='默认路径, 默认为空', max_length=200, verbose_name='默认路径, 默认为空'),
        ),
    ]
