# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-02 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='app类型', verbose_name='app类型')),
                ('name', models.CharField(help_text='App名字', max_length=20, verbose_name='App名字')),
                ('package', models.CharField(help_text='package下载地址', max_length=100, verbose_name='package下载地址')),
                ('package_name', models.CharField(help_text='package名称123', max_length=100, verbose_name='package名称123')),
                ('package_backup_path', models.CharField(help_text='package备份文件路径', max_length=100, verbose_name='package备份文件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('offer_url', models.CharField(help_text='offer', max_length=200, verbose_name='offer')),
                ('resc_path', models.CharField(blank=True, help_text='app资源文件路径', max_length=100, null=True, verbose_name='app资源文件路径')),
                ('offer_id', models.CharField(blank=True, help_text='offer_id', max_length=50, null=True, verbose_name='offer_id')),
                ('revenue', models.FloatField(default=0, help_text='收入', verbose_name='收入')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='国家名称')),
                ('code', models.CharField(default='', max_length=10, verbose_name='国家简称')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='汇率')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='country',
            field=models.ForeignKey(help_text='国家', on_delete=django.db.models.deletion.CASCADE, to='task.Country', verbose_name='国家'),
        ),
    ]
