# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='app类型', verbose_name='app类型')),
                ('name', models.CharField(help_text='App名字', max_length=20, verbose_name='App名字')),
                ('package', models.CharField(help_text='package下载地址', max_length=100, verbose_name='package下载地址')),
                ('package_name', models.CharField(help_text='package名称', max_length=100, verbose_name='package名称')),
                ('package_backup_path', models.CharField(help_text='package备份文件路径', max_length=100, verbose_name='package备份文件路径')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('offer_url', models.CharField(help_text='offer', max_length=200, verbose_name='offer')),
                ('resc_path', models.CharField(blank=True, help_text='app资源文件路径', max_length=100, null=True, verbose_name='app资源文件路径')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='国家名称')),
                ('code', models.CharField(default='', max_length=10, verbose_name='国家简称')),
                ('rate', models.FloatField(blank=True, default=0, null=True, verbose_name='汇率')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=20, verbose_name='name')),
                ('execute_time', models.DateTimeField(help_text='执行时间', max_length=20, verbose_name='执行时间')),
                ('execute_timezone', models.IntegerField(default=8, help_text='时区', verbose_name='时区')),
                ('count', models.IntegerField(default=0, help_text='任务数量', verbose_name='任务数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_finished', models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成')),
                ('app', models.ForeignKey(help_text='app', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='task.App', verbose_name='app')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='脚本名字', max_length=20, verbose_name='脚本名字')),
                ('path', models.CharField(help_text='script path', max_length=100, verbose_name='script path')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_finished', models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成')),
                ('schedule', models.ForeignKey(help_text='关联Schedule', on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='task.Schedule', verbose_name='关联Schedule')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedule',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_state', models.IntegerField(choices=[(3, 'success'), (2, 'complete'), (0, 'wait'), (1, 'start')], default=0, help_text='任务状态', verbose_name='任务状态')),
                ('will_recharge', models.BooleanField(default=False, help_text='是否充值', verbose_name='是否充值')),
                ('recharge_amount', models.FloatField(default=0, help_text='充值金额', verbose_name='充值金额')),
                ('pids', jsonfield.fields.JSONField(default=list, help_text='进程', verbose_name='进程')),
                ('config', jsonfield.fields.JSONField(default={}, help_text='详细信息', verbose_name='详细信息')),
                ('is_finished', models.BooleanField(default=False, help_text='是否完成', verbose_name='是否完成')),
                ('is_success', models.BooleanField(default=False, help_text='是否成功', verbose_name='是否成功')),
                ('begin_time', models.DateTimeField(blank=True, help_text='任务开始时间', null=True, verbose_name='任务开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='任务结束时间', null=True, verbose_name='任务结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ref_id', models.CharField(help_text='ref_id', max_length=100, verbose_name='ref_id')),
                ('is_need_reinstall', models.BooleanField(default=False, help_text='是否需要重新下载', verbose_name='是否需要重新下载')),
                ('package_backup_path', models.CharField(blank=True, help_text='任务备份文件路径', max_length=100, null=True, verbose_name='任务备份文件路径')),
                ('app_error_log', models.CharField(blank=True, help_text='app错误日志', max_length=1000, null=True, verbose_name='app错误日志')),
                ('error_log', models.CharField(blank=True, help_text='错误日志', max_length=1000, null=True, verbose_name='错误日志')),
                ('phone', models.ForeignKey(blank=True, help_text='Phone', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='device.Phone', verbose_name='Phone')),
                ('prev_task', models.ForeignKey(blank=True, help_text='上一步流程', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_next', to='task.Task', verbose_name='上一步流程')),
                ('script', models.ForeignKey(help_text='task', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='task.Script', verbose_name='脚本')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Task',
            },
        ),
        migrations.AddField(
            model_name='app',
            name='country',
            field=models.ForeignKey(help_text='国家', on_delete=django.db.models.deletion.CASCADE, to='task.Country', verbose_name='国家'),
        ),
    ]
