# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-27 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'IOS')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
        migrations.AlterField(
            model_name='script',
            name='name',
            field=models.CharField(help_text='脚本名字', max_length=100, verbose_name='脚本名字'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.IntegerField(choices=[(3, 'success'), (1, 'start'), (0, 'wait'), (2, 'complete')], default=0, help_text='任务状态', verbose_name='任务状态'),
        ),
    ]
