# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-04 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='title', max_length=50, verbose_name='title')),
                ('author', models.CharField(help_text='author', max_length=20, verbose_name='author')),
                ('innerhtml', models.TextField(help_text='文章主体内容', max_length=3000, verbose_name='文章主体内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='文章创建时间', verbose_name='文章创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='文章修改时间', verbose_name='文章修改时间')),
                ('readed_number', models.IntegerField(default=1, help_text='阅读数', verbose_name='阅读数')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'IOS')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
    ]
