# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-05 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20190904_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='App名字', max_length=20, verbose_name='App名字')),
                ('package', models.CharField(help_text='package下载地址', max_length=100, verbose_name='package下载地址')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'App',
            },
        ),
        migrations.RemoveField(
            model_name='app',
            name='country',
        ),
        migrations.DeleteModel(
            name='App',
        ),
    ]
