# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-09-20 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190905_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgs',
            name='name',
            field=models.CharField(help_text='图片名字', max_length=20, verbose_name='图片名字'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='package',
            field=models.CharField(help_text='图片下载地址', max_length=100, verbose_name='图片下载地址'),
        ),
    ]
