# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190628_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.IntegerField(choices=[(2, 'complete'), (1, 'start'), (0, 'wait'), (3, 'success')], default=0, help_text='任务状态', verbose_name='任务状态'),
        ),
    ]
