# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-28 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190628_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.IntegerField(choices=[(0, 'wait'), (1, 'start'), (3, 'success'), (2, 'complete')], default=0, help_text='任务状态', verbose_name='任务状态'),
        ),
    ]
