# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-06-28 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20190628_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_finished',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_success',
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'IOS')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_state',
            field=models.IntegerField(choices=[(1, 'start'), (3, 'success'), (2, 'complete'), (0, 'wait')], default=0, help_text='任务状态', verbose_name='任务状态'),
        ),
    ]
