# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-05 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20190629_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='offer_id',
            field=models.CharField(blank=True, help_text='offer_id', max_length=50, null=True, verbose_name='offer_id'),
        ),
        migrations.AddField(
            model_name='app',
            name='revenue',
            field=models.FloatField(default=0, help_text='收入', verbose_name='收入'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_conversion',
            field=models.BooleanField(default=False, help_text='是否转化', verbose_name='是否转化'),
        ),
        migrations.AddField(
            model_name='task',
            name='revenue',
            field=models.FloatField(default=0, help_text='收入', verbose_name='收入'),
        ),
    ]
