# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-08 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190705_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='app_info_log',
            field=models.CharField(blank=True, help_text='app日志', max_length=1000, null=True, verbose_name='app日志'),
        ),
    ]
