# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-09 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_app_info_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'IOS')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
        migrations.AlterField(
            model_name='task',
            name='app_error_log',
            field=models.TextField(blank=True, help_text='app错误日志', max_length=100000, null=True, verbose_name='app错误日志'),
        ),
        migrations.AlterField(
            model_name='task',
            name='app_info_log',
            field=models.TextField(blank=True, help_text='app日志', max_length=100000, null=True, verbose_name='app日志'),
        ),
        migrations.AlterField(
            model_name='task',
            name='error_log',
            field=models.TextField(blank=True, help_text='错误日志', max_length=100000, null=True, verbose_name='错误日志'),
        ),
    ]
