# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-10 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20190709_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False, help_text='是否激活', verbose_name='是否激活'),
        ),
    ]
