# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-10 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_task_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='click_ip',
            field=models.CharField(blank=True, help_text='click ip', max_length=100, null=True, verbose_name='click ip'),
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
    ]
