# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-10 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_auto_20190710_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(0, 'Android'), (1, 'IOS')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
    ]
