# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-18 02:51
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_auto_20190710_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.FloatField(default=0, help_text='收入', verbose_name='收入')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ref_id')),
                ('click_ip', models.CharField(blank=True, max_length=16, null=True, verbose_name='ref_id')),
                ('offer_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ref_id')),
                ('original', jsonfield.fields.JSONField(default=dict, verbose_name='原始数据')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
