# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-18 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0015_postback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postback',
            options={'verbose_name': 'PostBack', 'verbose_name_plural': 'PostBack'},
        ),
        migrations.AlterField(
            model_name='app',
            name='platform',
            field=models.IntegerField(choices=[(1, 'IOS'), (0, 'Android')], default=1, help_text='app类型', verbose_name='app类型'),
        ),
        migrations.AlterField(
            model_name='postback',
            name='offer_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='offer_id'),
        ),
    ]
