# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-07-18 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0016_auto_20190718_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postback',
            name='click_ip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='click_ip'),
        ),
    ]
