"""
Django settings for sp_backend project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from .base import *
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'CONN_MAX_AGE': 14400,
        'NAME': 'emu_master',
        'USER': 'emu_master_user',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


FILE_PATH_PREFIX = "/home/ftp/file/"
APP_FOLDER = "app"
SCRIPT_FOLDER = "script"
APP_RESC_FOLDER = "app_resc"

CRONTAB_DJANGO_SETTINGS_MODULE = "settings.prod"
CRONJOBS = [
    # 生成统计数据
    ('*/1 * * * *', 'apps.device.check_heartbeat.check_phone'),
    ('*/1 * * * *', 'apps.device.check_heartbeat.check_slave')
]
SLAVE_PORT = 8000
